### ISSUE TITLE
Date on blog posts

### ISSUE THREAD

**Issue by lannonbr** [ChristopherBiscardi/christopherbiscardi.github.com#89]
So I see that each of your blog posts do have a date field in the frontmatter. I would love to see the date displayed in the article on your site.

**Comment by ChristopherBiscardi** [comment]
I've thought about this a bunch since you posted this issue and I think I'm going to stick with my initial inclination to not put dates on my content. I want to bias myself towards creating evergreen content more than date-restricted content and after following up with a bunch of people asking why they wanted to see dates, none produced a compelling reason (it seems to only immediately deteriorate the value of the content for no reason). A much more compelling approach seems to be to store and display metadata so that when a blog post talks about specific versions of software, that is clearly indicated.

Thanks for filing the issue :)
